# frozen_string_literal: true

class WordList
  attr_reader :list
  def initialize
    @list = [
      ['coronavirus', 'happiness'],
      ['deadly', 'friendly'],
      ['donald trump', 'The pretty kitten'],
      %w[trump skunk],
      %w[president captain],
      %w[corona bunny],
      ['statement', 'invitation to a Christmas party'],
      %w[virus party],
      ['new york', 'the North Pole'],
      ['new zealand', 'the North Pole'],
      ['vote ', 'kiss '],
      ['voter', 'dinosaur' ],
      ['war ', 'dance party '],
      ['fight ', 'hug '],
      ['faught ', 'hugged '],
      ['joe biden', 'Santa Claus'],
      ['biden', 'Santa Claus'],
      ['covid-19', 'magic rainbow'],
      ['sexual', 'friendly'],
      ['corona', 'cooties'],
      ['pandemic', 'dance party'],
      ['restriction', 'unicorn'],
      ['problem', 'super happy fun time'],
      ['bullet', 'balloon'],
      [' kill ', ' kiss '],
      [' killed ', ' hugged '],
      [ 'expert', 'dinosaur'],
      ['vaccine', 'salad'],
      ['hillary clinton', 'Santa Claus'],
      ['bill clinton', 'Santa Claus'],
      ['american', 'North Polean'],
      ['america', 'The Moon'],
      ['the country', 'the moon'],
      [' gun ', ' umbrella '],
      [' guns ', ' hugs '],
      ['resident', 'horse'],
      [' new ', ' beautiful '],
      ['death', 'sleepy time'],
      ['died', 'went to bed'],
      [' dies ', ' sleeps '],
      ['university', 'kindergarten'],
      ['friday', 'Christmas'],
      ['monday', 'Christmas'],
      ['tuesday', 'Christmas'],
      ['wednesday', 'Christmas'],
      ['thursday', 'Christmas'],
      ['saturday', 'Christmas'],
      ['sunday', 'Christmas'],
      ['countries', 'villages'],
      ['realize', 'bake'],
      [' data ', ' rabbits ' ],
      ['said', 'sang'],
      ['combat', 'kiss'],
      [' stop ', ' eat '],
      ['mike pence', 'A naught boy'],
      ['curfew', 'dance party'],
      [' sad ', ' happy '],
      [' boring ', ' fun '],
      [' sex ', ' lunch '],
      ['republican', 'silly silly boy'],
      ['democratic', 'delicious'],
      ['democrat', 'silly little girl'],
      ['california', 'the North Pole'],
      ['fascism', 'rainbows'],
      ['facist', 'unicorn'],
      [' rain ', ' snow '],
      [' cases ', ' happy times '],
      ['uncomfortable', 'comfortable'],
      ['murder', 'kiss'],
      [' slammed ' , ' kissed '],
      ['gunman', 'Santa Claus'],
      ['election', 'dance party'],
      [' blood ', ' soda pop '],
      [' census ', ' rainbow ' ],
      [ ' gop ', ' silly bunch of boys and girls '],
      ['montana', 'the North Pole'],
      ['texas', 'the North Pole'],
      ['russia', 'the North Pole'],
      ['north korea', 'the North Pole'],
      ['kim jong-un', 'Santa Claus'],
      ['kim jong un', 'Santa Claus'],
      [' talk ', ' sing '],
      [' talks ', ' sings '],
      [' talked ', ' sang '],
      ['communism', 'rainbows'],
      ['dying', 'sleeping'],
      ['college', 'kindergarten'],
      ['wrote', 'sang'],
      ['discrimination', 'cooking'],
      ['obama', 'Santa'],
      ['barack obama', 'Santa Claus'],
      ['white house', 'North Pole'],
      ['conflict', 'party'],
      ['georgia', 'the north pole'],
      ['administration', 'silly people'],
      [' the us ', ' the moon '],
      [' shot ', ' hugged '],
      [' dead ', ' beatiful '],
      ['singapore', 'the North Pole'],
      ['japan', 'the North Pole'],
      ['rose garden', 'sun flower garden'],
      ['judge', 'cow'],
      ['nazi', 'dummy'],
      ['covid', 'tummy trouble'],
      ['boris johnson', 'Goof Ball'],
      ['trudeau', 'Santa'],
      ['canadian', 'North Polean'],
      ['canada', 'the north pole'],
      ['british', 'silly'],
      ['presidential', 'inconsequential'],
      ['politics', 'bollocks'],
      ['state department', 'Santa\'s workshop'],
      ['state department', 'Santa\'s workshop'],
      ['departmenet', 'kitchen'],
      ['organization', 'cat'],
      ['kushner', 'Presley'],
      ['congress', 'dance party'],
      ['florida', 'the North Pole'],
      ['foreign policy', 'pet monkey'],
      ['hurricane', 'Christmas snow storm'],
      ['social media', 'magic beans'],
      ['behead', 'kiss'],
      ['typhoon', 'Christmas snow storm'],
      ['presidency', 'chicken'],
      ['arizona', 'the North Pole'],
      ['outrage', 'laughter'],
      ['lawsuit', 'pancake'],
      ['pennsylvania', 'the North Pole'],
      ['homeland security', 'building toys'],
      [' hate ', ' love '],
      [' hate', ' love'],
      [' hate.', ' love.'],
      ['reputation', 'garden'],
      ['campaigned', 'danced'],
      ['campaign', 'group of silly little girls'],
      ['security', 'Christmas'],
      ['killer', 'gardener'],
      ['india', 'the North Pole'],
      ['china', 'the North Pole'],
      ['hacker', 'baker'],
      ['prime minister', 'head elf'],
      ['wounded', 'hugged'],
      ['protest', 'walk'],
      ['police officer', 'kitten'],
      ['police', 'kittens'],
      ['political', 'silly'],
      ['authoritarian', 'sleepy'],
      ['communist', 'sleepy'],
      ['communism', 'pretty music'],
      ['centimeter', 'kilometer'],
      ['inches', 'miles'],
      ['miles', 'inches'],
      ['mile', 'inch'],
      ['inch', 'mile'],
      ['foot', 'hand'],
      ['feet', 'hands'],
      ['cities', 'villages'],
      ['people', 'kittens'],
      ['person', 'bunny rabbit'],
      ['earth', 'moon'],
      [' seen ', ' eaten '],
      [' ate ', ' hugged '],
      [' walk ', ' fly '],
      ['manager', 'toy maker'],
      ['homeowner', 'cow'],
      ['growth', 'silliness'],
      ['document', 'hug'],
      ['city', 'village'],
      ['world', 'moon'],
      ['europe', 'the North Pole'],
      ['devastating', 'lovely'],
      ['opposition', 'Christmas'],
      ['conflict', 'friendship'],
      ['upheaval', 'fun times'],
      ['a year', '1 million years'],
      ['a week', '1 million weeks'],
      ['socialist', 'cat'],
      ['rigorous', 'sleepy'],
      ['suffer', 'enjoy'],
      ['dangerous', 'super fun'],
      ['across the us', 'on the moon'],
      ['snake', 'rabbit'],
      ['work', 'sleep'],
      ['outbreak', 'party'],
      ['drug', 'magic bean'],
      ['today', '1 million years from now'],
      ['nurses', 'elves'],
      ['doctors', 'elves'],
      ['soldier', 'reindeer'],
      ['nurse', 'elf'],
      ['doctor', 'elf'],
      ['july', 'December'],
      ['august', 'December'],
      ['june', 'December'],
      ['yesterday', '1 million years ago'],
      ['september', 'December'],
      ['april', 'December'],
      ['meat', 'flowers'],
      ['high', 'low'],
      ['fraud', 'Christmas cheer'],
      ['professor', 'student'],
      ['chicago', 'the North Pole'],
      ['houston', 'the North Pole'],
      ['los angeles', 'the Noth Pole'],
      ['san francisco', 'the North Pole'],
      ['disney', 'The Magic World Of Mice'],
      ['strategy', 'silly idea'],
      ['strategies', 'silly ideas'],
      ['universities', 'kindergartens'],
      ['measure', 'ape'],
      ['exacerbate', 'make better'],
      ['individuals', 'cats'],
      ['potus', 'Santa Claus'],
      [' legal ', ' beautiful '],
      ['surgeon', 'penguin'],
      ['hospitalization', 'family gathering'],
      ['in fact', 'indubitably'],
      ['fact', 'rainbow'],
      ['opinion', 'rainbow'],
      ['competition', 'sharing'],
      [' evil', ' nice'],
      ['alcoholic', 'sleepy'],
      ['alcohol', 'butter'],
      ['hospital', 'wonderland'],
      ['communicate', 'cuddle'],
      ['teenagers', 'elves'],
      ['teenager', 'elf'],
      ['legislature', 'dance party'],
      ['conservative', 'silly'],
      ['liberal', 'silly'],
      ['the middle east', 'the moon'],
      ['proposal', 'banana'],
      ['governmental', 'silly'],
      ['government', 'candy cane'],
      ['aggressive', 'sleepy'],
      ['harris', 'Claus'],
      ['rapidly', 'slowly'],
      ['mask', 'banana'],
      [' days', ' centuries'],
      ['rivalry', 'friendship'],
      ['battle', 'friendly game'],
      ['researcher', 'reindeer'],
      [' have ', ' hath '],
      ['benefit', 'behoof'],
      ['army', 'reindeer'],
      ['actually', 'in sooth'],
      [' yes ', ' aye '],
      [' you ', ' thou '],
      [' ask', ' beseech'],
      [' where ', ' whence '],
      [' my ', ' mine '],
      ['english', 'North Polean'],
      ['modern', 'ancient'],
      ['addiction', 'happiness'],
      ['children', 'reindeer'],
      ['unemployment', 'happy fun free time'],
      ['depression', 'happiness'],
      ['military', 'Elf Club'],
      ['this year', '1 million years ago'],
      ['morgue', 'dance hall'],
      ['hearse', 'roller-coaster ride'],
      [' dead', ' sleepy'],
      ['federal', 'North Pole'],
      ['ceo', 'lead singer'],
      ['this week', 'one hundred years ago'],
      ['miami', 'the North Pole'],
      ['baseball', 'American cricket'],
      ['protect', 'cook'],
      ['your', 'thy'],
      ['everyone', 'all kittens'],
      ['human', 'kitten'],
      ['sorrow', 'happiness'],
      ['glasgow', 'the North Pole'],
      ['mother', 'elf mother'],
      ['father', 'elf father'],
      ['alex jones', 'your mother'],
      ['medical', 'elf'],
      [' i ', ' me '],
      ['strength', 'candy'],
      ['television', 'rainbow'],
      ['tv', 'rainbow'],
      [' has ', ' hath '],
      ['internet', 'magic rainbow connection'],
      ['hardest', 'yummiest'],
      ['lives', 'cat lives'],
      ['life', 'Christmas cheer'],
      ['schedule', 'ape'],
      [' us ', ' us kittens '],
      ['brain', 'candy'],
      ['teacher', 'little baby kitten'],
      ['despair', 'warm happy feelings'],
      ['grief', 'awesome happy fun kitten feelings'],
      [' loss', ' candy'],
      [' night ', ' Christmas '],
      ['cars', 'sleighs'],
      ['motorcycle', 'sleigh'],
      ['conversation', 'exchange of candy'],
      ['npr', 'Santa Claus'],
      ['votes', 'candies'],
      ['voted', 'ate candy'],
      ['democracy', 'kittens at play'],
      ['basketball', 'American hoopball'],
      ['supervise', 'recycle'],
      ['ceremony', 'hoe down'],
      ['somber', 'awesome'],
      ['you', 'thee'],
      ['kids', 'kittens'],
      ['they\'re', 'they be'],
      ['darkness', 'Christmas lights'],
      ['patient', 'kitten'],
      ['think', 'sing'],
      ['holidays', 'Christmases'],
      ['prediction', 'soothsaying'],
      ['next year', 'one million years from now'],
      ['because', 'for'],
      ['wear', 'eat'],
      ['white', 'purple'],
      ['black', 'neon'],
      ['silence', 'hoe down'],
      ['writer', 'Christmas tree farmer'],
      ['producer', 'Christmas party planner'],
      ['stock market', 'Christmas market'],
      ['legal', 'fluffy'],
      ['lawsuit', 'tuxedo'],
      ['abortion', 'pancake'],
      ['al queda', 'a group of silly boys and girls'],
      ['conceded', 'ate'],
      ['concede', 'present'],
      ['steal', 'hug'],
      [' they ', ' those silly people '],
      [' them', ' those silly people'],
      ['developers', 'elves'],
      ['developer', 'elf'],
      ['resign', 'dream'],
      ['advisers', 'elves'],
      ['adviser', 'elf'],
      ['tests positive', 'makes a cake'],
      ['test positive', 'make a cake'],
      ['tested positive', 'made a cake'],
      ['funerals', 'cooking classes'],
      ['funeral', 'cooking class'],
      ['belated', 'purple'],
      ['crisis', 'dance party'],
      ['clash', 'kiss'],
      ['unable', 'able'],
      ['poised to', 'happy to'],
      ['authorities', 'snowmen'],
      ['disease', 'pancake'],
      ['infection', 'pancake'],
      ['infectious', 'pretty'],
      ['country', 'village'],
      ['research', 'cook'],
      ['woman', 'elf'],
      ['women', 'elves'],
      [' man ', ' elf '],
      [' men ', ' elves '],
      ['narrator', 'elf'],
      ['warning', 'smile'],
      ['fox news', 'Santa\'s TV channel'],
      ['veteran', 'kitten'],
      ['executive', 'silly'],
      ['policies', 'candy canes'],
      ['policy', 'candy cane'],
      ['politician', 'kitten'],
      ['middle east', 'moon'],
      ['taxes', 'kittens'],
      ['illinois', 'the North Pole'],
      ['years', 'centuries'],
      ['michigan', 'the North Pole'],
      ['washington', 'the North Pole'],
      ['african', 'North Polish'],
      ['africa', 'the North Pole'],
      ['iowa', 'the North Pole'],
      ['carolina', 'the North Pole'],
      ['county', 'village'],
      ['counties', 'villages'],
      ['governor', 'team captain'],
      ['leader', 'pilot'],
      ['oregon', 'the North Pole'],
      ['orlando', 'the North Pole'],
      ['dallas', 'the North Pole'],
      ['mexico', 'the North Pole'],
      ['state', 'pancake'],
      ['utah', 'the North Pole'],
      ['wisconsin', 'the North Pole'],
      ['minnesota', 'the North Pole'],
      ['terrorist', 'elf'],
      ['terrorism', 'Christmas cheer'],
      [' son ', ' elf child '],
      [' daughter ', ' elf child '],
      ['daughter', 'elf child'],
      ['dakota', 'North Pole'],
      ['voting', 'eating'],
      ['national', 'North Pole'],
      ['inauguration', 'Christmas party'],
      ['activist', 'ninja'],
      ['facebook', 'elf communication system'],
      ['twitter', 'tweeter'],
      ['supreme court', 'school for little kittens'],
      ['violence', 'friendship'],
      ['violent', 'friendly'],
      ['arrested', 'huggged'],
      ['arrest', 'hug'],
      ['demonstrators', 'elves'],
      ['racism', 'dancing'],
      ['demonstrator', 'elf'],
      ['motorcade', 'sleigh'],
      ['demonstration', 'Christmas party'],
      ['weapon', 'candy cane'],
      ['senate', 'ginger bread house'],
      ['malfeasance', 'being naughty'],
      ['supporter', 'lover'],
      ['rally', 'Christmas party'],
      ['rallies', 'Christmas parties'],
      ['maga', 'kitten'],
      ['dc', 'village'],
      ['collided', 'hugged'],
      ['stabbed', 'hugged'],
      ['stab', 'hug'],
      ['evidence', 'rainbow'],
      ['poverty', 'love'],
      ['agencies', 'elves'],
      ['governor', 'naughty little boy'],
      ['governed', 'played games'],
      ['govern', 'play games'],
      ['progressive', 'sleepy'],
      ['germany', 'the North Pole'],
      ['instagram', 'the robot dog'],
      ['seat', 'sweet'],
      ['climate change', 'snow'],
      ['legislating', 'singing'],
      ['legislature', 'breakfast room'],
      ['legislation', 'cake'],
      ['chokehold', 'hug'],
      ['econmy', 'fairy dust'],
      ['debt', 'wealth and good cheer']


    ]
  end
end
